"""Initial migration

Revision ID: 8c8c247d930e
Revises: 
Create Date: 2025-04-11 10:04:27.286517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c8c247d930e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odds', schema=None) as batch_op:
        batch_op.alter_column('bookmakers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('odds_game_id_key', type_='unique')
        batch_op.drop_constraint('unique_event_bookmakers_market_outcome', type_='unique')
        batch_op.drop_constraint('unique_event_commence_time', type_='unique')
        batch_op.create_unique_constraint('unique_odds_entry', ['event_id', 'bookmakers', 'market', 'outcome'])
        batch_op.drop_column('point')
        batch_op.drop_column('odds_type')
        batch_op.drop_column('price')

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('event_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_constraint('scores_game_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'odds', ['event_id'], ['event_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('scores_game_id_fkey', 'odds', ['event_id'], ['event_id'], ondelete='CASCADE')
        batch_op.alter_column('event_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('odds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('odds_type', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('point', sa.NUMERIC(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('unique_odds_entry', type_='unique')
        batch_op.create_unique_constraint('unique_event_commence_time', ['event_id', 'commence_time'])
        batch_op.create_unique_constraint('unique_event_bookmakers_market_outcome', ['event_id', 'bookmakers', 'market', 'outcome'])
        batch_op.create_unique_constraint('odds_game_id_key', ['event_id'])
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('bookmakers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
